%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-rmf-charging-schedule
Version:        2.10.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS rmf_charging_schedule package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kilted-rclpy
Requires:       ros-kilted-rmf-fleet-msgs
Requires:       ros-kilted-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-kilted-rclpy
BuildRequires:  ros-kilted-rmf-fleet-msgs
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Node for a fixed 24-hour rotating charger usage schedule

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/kilted"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Tue May 20 2025 Grey <mxgrey@intrinsic.ai> - 2.10.1-1
- Autogenerated by Bloom

* Tue Jun 11 2024 Grey <mxgrey@intrinsic.ai> - 2.7.1-1
- Autogenerated by Bloom

* Sun Jun 09 2024 Grey <mxgrey@intrinsic.ai> - 2.7.0-1
- Autogenerated by Bloom

* Wed Mar 13 2024 Grey <mxgrey@intrinsic.ai> - 2.6.0-1
- Autogenerated by Bloom

* Fri Mar 08 2024 Grey <mxgrey@intrinsic.ai> - 2.5.0-2
- Autogenerated by Bloom

* Fri Dec 22 2023 Grey <mxgrey@intrinsic.ai> - 2.5.0-1
- Autogenerated by Bloom

* Tue Dec 19 2023 Grey <mxgrey@intrinsic.ai> - 2.4.0-1
- Autogenerated by Bloom

